# Spike Workflow
# 기술 검증 (PoC) 워크플로우

name: spike
displayName: "기술 검증 (Spike)"
description: "새로운 기술이나 접근 방식을 검증하기 위한 워크플로우"

triggers:
  keywords:
    - "검증"
    - "PoC"
    - "프로토타입"
    - "실험"
    - "테스트해봐"
    - "가능한지"
    - "spike"
    - "prototype"
  explicit: "/workflow spike"

steps:
  - id: research
    name: "기술 조사"
    agent: agent-backend
    input: "{{request}}"
    output: "조사 결과"
    description: |
      기술 검증을 위한 사전 조사를 수행합니다.
      - 기술 스택 분석
      - 유사 사례 조사
      - 제약 사항 파악

  - id: prototype
    name: "프로토타입 구현"
    agent: agent-backend
    input: "{{steps.research.output}}"
    output: "프로토타입 코드"
    description: |
      최소 기능 프로토타입을 구현합니다.
      - 핵심 기능만 구현
      - 빠른 검증 우선
      - 완성도보다 실행 가능성

  - id: evaluate
    name: "결과 평가"
    agent: agent-backend
    input: "{{steps.prototype.output}}"
    output: "평가 리포트"
    gate: user_approval
    description: |
      프로토타입 결과를 평가합니다.
      - 기술 적합성 판단
      - 성능 측정
      - 도입 가능성 평가

  - id: document
    name: "결과 문서화"
    agent: agent-docs
    input: "{{steps.evaluate.output}}"
    output: "docs/spikes/{{taskId}}-spike-result.md"
    condition: "agents.docs.enabled"
    description: |
      검증 결과를 문서화합니다.
      - 검증 목적 및 배경
      - 검증 방법
      - 결과 및 결론
      - 권장 사항

gates:
  user_approval:
    description: "결과 검토"
    type: manual
    prompt: "프로토타입 결과를 검토하시겠습니까?"

outcomes:
  success:
    description: "기술 검증 성공 - 본 개발 진행 권장"
    nextWorkflow: "full-feature"

  partial:
    description: "부분 성공 - 추가 검증 필요"
    nextWorkflow: "spike"

  failure:
    description: "검증 실패 - 대안 검토 필요"
    nextWorkflow: null

estimatedDuration: "2시간 ~ 1일"
priority: medium
