openapi: 3.0.3
info:
  title: API 명세
  description: |
    API 명세 템플릿입니다.
    프로젝트에 맞게 수정하여 사용하세요.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:8080
    description: Local Development
  - url: https://api.staging.example.com
    description: Staging
  - url: https://api.example.com
    description: Production

tags:
  - name: example
    description: 예시 API

paths:
  /api/v1/examples:
    get:
      tags:
        - example
      summary: 목록 조회
      description: 예시 목록을 조회합니다.
      operationId: getExamples
      parameters:
        - name: page
          in: query
          description: 페이지 번호 (0부터 시작)
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: 페이지 크기
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleListResponse'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 인증 필요
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

    post:
      tags:
        - example
      summary: 생성
      description: 새 예시를 생성합니다.
      operationId: createExample
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateExampleRequest'
      responses:
        '201':
          description: 생성됨
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

  /api/v1/examples/{id}:
    get:
      tags:
        - example
      summary: 단건 조회
      description: ID로 예시를 조회합니다.
      operationId: getExample
      parameters:
        - name: id
          in: path
          required: true
          description: 예시 ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
        '404':
          description: 찾을 수 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

    put:
      tags:
        - example
      summary: 수정
      description: 예시를 수정합니다.
      operationId: updateExample
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateExampleRequest'
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
      security:
        - bearerAuth: []

    delete:
      tags:
        - example
      summary: 삭제
      description: 예시를 삭제합니다.
      operationId: deleteExample
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 삭제됨
        '404':
          description: 찾을 수 없음
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ExampleResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 고유 ID
        name:
          type: string
          description: 이름
        status:
          type: string
          enum: [ACTIVE, INACTIVE]
          description: 상태
        createdAt:
          type: string
          format: date-time
          description: 생성일시
        updatedAt:
          type: string
          format: date-time
          description: 수정일시
      required:
        - id
        - name
        - status
        - createdAt

    ExampleListResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ExampleResponse'
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
        totalPages:
          type: integer

    CreateExampleRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: 이름
      required:
        - name

    UpdateExampleRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        status:
          type: string
          enum: [ACTIVE, INACTIVE]

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: 에러 코드
        message:
          type: string
          description: 에러 메시지
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string
        timestamp:
          type: string
          format: date-time
        traceId:
          type: string
          description: 추적 ID
      required:
        - code
        - message
        - timestamp
